project:
  type: manuscript
  output-dir: docs
  render:
    - notebooks/geo_data_cleaning.qmd
    - notebooks/analysis.qmd
    - index.qmd

manuscript:
  article: index.qmd

execute:
  echo: false

format:
  html:
    page-layout: article
    smooth-scroll: true
    link-external-window: true
    theme:
      - ../.style/switchbox.scss
    include-after-body: ../.style/switchbox.html


    fig-dpi: 300
    fig-format: png
